### ISSUE TITLE
[question] What does kubenix do?

### ISSUE THREAD

**Issue by hansbogert** [xtruder/kubenix#21]
Coming from a kubernetes background and have little exposure to Nix, what would Kubenix do for me? The term 'resource builder' is not really evident to me.

**Comment by pauldub** [comment]
Kubenix is a nix library that allows to build kubernetes manifests using nix expressions. It allows building abstraction thanks to its module system and integrates with the nix ecosystem.

**Comment by hansbogert** [comment]
Would this be a means to deploy k8s nodes with immutable kubernetes images, e.g., a k8s master? In a way, would this be an alternative, or have overlap with the functionality of kubeadm? (I don't mean overlap in any negative way!, I'm just trying to figure out where this fits)

**Comment by pauldub** [comment]
No, kubenix allows to describe kubernetes resources such as Deployments, Ingresses, etc. 

Althought nixos has support for setting up kubernetes: https://nixos.org/nixos/options.html#kubernetes

**Comment by euank** [comment]
I'll add my own "kubenix is like" since hopefully more explanations will help!

The things in the k8s ecosystem that kubenix is most like are the following:

1. [ksonnet](https://github.com/ksonnet/ksonnet) / jsonnet
    Those tools are both concerned with generating k8s resources, such as deployments, but doing so in a language that allows importing libraries, reusing config snippets, etc
2. [skycfg](https://github.com/stripe/skycfg)
    This is stripe's answer to the same problem of generating k8s resources
3. A bunch of other tools in [this document](https://docs.google.com/spreadsheets/d/1FCgqz1Ci7_VCz_wdh8vBitZ3giBtac_H8SBw4uxnrsE/edit#gid=0) (thanks brian grant!)

Kubenix is unusual in that it can also use `nix`'s other features to do things like build docker images as well, which most of those other tools don't deal with.

One other thing that may help you would be to read through the [example in the repo](https://github.com/xtruder/kubenix/blob/611059a329493a77ec0e862fcce4671cd3768f32/examples/nginx-deployment/module.nix#L11-L64).

That shows a nix expression that can be evaluated into a kubectl-applyable kubernetes deployment.

One benefit of writing it in nix instead of in yaml directly is that nix is a much safer language (i.e. indentation doesn't matter), it has handy features like functions, the ability to import / reference things, variables, built-in string templating, etc.

**Comment by hansbogert** [comment]
Thank you for the answers, this clears up quite a few things. I was approaching this from the underlay/ infrastructure side.
